name: Unit Testing

on:
  pull_request:
    branches: [ master, develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '14'

    - name: Run npm install
      run: npm install

    - name: Run npm test
      run: npm test
